apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-devops-agent
  template:
    metadata:
      labels:
        app: azure-devops-agent
    spec:
      containers:
      - name: azure-devops-agent
        image: alperanfk/helloworldagent:0.0.1 
        env:
        - name: AZP_URL
          value: "https://dev.azure.com/furkankaya35"
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azure-devops-pat
              key: AZP_TOKEN
        - name: AZP_AGENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AZP_POOL
          value: "AFK"