apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-html
data:
  welcome.html: |-
    <!DOCTYPE html>
    <html>
    <body>
    <h1>Welcome to My Custom Page</h1>
    <p>This is a custom welcome page.</p>
    </body>
    </html>
